const weekdayOptions = [
  'Dushanba',
  'Seshanba',
  'Chorshanba',
  'Payshanba',
  'Juma',
  'Shanba',
  'Yakshanba',
]

const roleOptions = ['ADMIN', 'EDITOR', 'VIEWER']

export const modules = [
  {
    key: 'schools',
    title: 'Maktablar',
    icon: 'school',
    endpoint: '/api/schools',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'name', label: 'Nomi', field: 'name', sortable: true, align: 'left' },
      { name: 'address', label: 'Manzil', field: 'address', align: 'left' },
    ],
    fields: [
      { key: 'name', label: 'Nomi', type: 'text', required: true },
      { key: 'address', label: 'Manzil', type: 'text', required: true },
    ],
  },
  {
    key: 'buildings',
    title: 'Binolar',
    icon: 'apartment',
    endpoint: '/api/buildings',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'name', label: 'Nomi', field: 'name', sortable: true, align: 'left' },
      { name: 'schoolName', label: 'Maktab', field: 'schoolName', align: 'left' },
    ],
    fields: [
      { key: 'name', label: 'Nomi', type: 'text', required: true },
      {
        key: 'schoolId',
        label: 'Maktab',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/schools',
        optionValue: 'id',
        optionLabel: 'name',
      },
    ],
  },
  {
    key: 'rooms',
    title: 'Xonalar',
    icon: 'meeting_room',
    endpoint: '/api/rooms',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'roomNumber', label: 'Xona raqami', field: 'roomNumber', sortable: true, align: 'left' },
      { name: 'capacity', label: "Sig'im", field: 'capacity', align: 'left' },
      { name: 'buildingName', label: 'Bino', field: 'buildingName', align: 'left' },
    ],
    fields: [
      { key: 'roomNumber', label: 'Xona raqami', type: 'text', required: true },
      { key: 'capacity', label: "Sig'im", type: 'number', required: true },
      {
        key: 'buildingId',
        label: 'Bino',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/buildings',
        optionValue: 'id',
        optionLabel: 'name',
      },
    ],
  },
  {
    key: 'academic-years',
    title: "O'quv yillari",
    icon: 'event',
    endpoint: '/api/academic-years',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'title', label: 'Sarlavha', field: 'title', sortable: true, align: 'left' },
      { name: 'startDate', label: 'Boshlanish', field: 'startDate', align: 'left' },
      { name: 'endDate', label: 'Tugash', field: 'endDate', align: 'left' },
      { name: 'schoolName', label: 'Maktab', field: 'schoolName', align: 'left' },
    ],
    fields: [
      { key: 'title', label: 'Sarlavha', type: 'text', required: true },
      { key: 'startDate', label: 'Boshlanish sanasi', type: 'date', required: true },
      { key: 'endDate', label: 'Tugash sanasi', type: 'date', required: true },
      {
        key: 'schoolId',
        label: 'Maktab',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/schools',
        optionValue: 'id',
        optionLabel: 'name',
      },
    ],
  },
  {
    key: 'school-classes',
    title: 'Sinflar',
    icon: 'groups',
    endpoint: '/api/school-classes',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'gradeNumber', label: 'Sinf', field: 'gradeNumber', sortable: true, align: 'left' },
      { name: 'sectionLetter', label: 'Harf', field: 'sectionLetter', align: 'left' },
      { name: 'maxStudents', label: 'Maks. o\'quvchi', field: 'maxStudents', align: 'left' },
      { name: 'academicYearTitle', label: "O'quv yili", field: 'academicYearTitle', align: 'left' },
    ],
    fields: [
      { key: 'gradeNumber', label: 'Sinf raqami', type: 'number', required: true },
      { key: 'sectionLetter', label: 'Harf', type: 'text', required: true },
      { key: 'maxStudents', label: "Maksimal o'quvchilar soni", type: 'number', required: true },
      {
        key: 'academicYearId',
        label: "O'quv yili",
        type: 'select',
        required: true,
        optionsEndpoint: '/api/academic-years',
        optionValue: 'id',
        optionLabel: 'title',
      },
    ],
  },
  {
    key: 'students',
    title: "O'quvchilar",
    icon: 'face',
    endpoint: '/api/students',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'fullName', label: "To'liq ism", field: 'fullName', sortable: true, align: 'left' },
      { name: 'birthDate', label: "Tug'ilgan sana", field: 'birthDate', align: 'left' },
      { name: 'className', label: 'Sinf', field: 'className', align: 'left' },
    ],
    fields: [
      { key: 'firstName', label: 'Ism', type: 'text', required: true },
      { key: 'lastName', label: 'Familiya', type: 'text', required: true },
      { key: 'birthDate', label: "Tug'ilgan sana", type: 'date', required: true },
      {
        key: 'schoolClassId',
        label: 'Sinf',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/school-classes',
        optionValue: 'id',
        optionLabel: (item) => `${item.gradeNumber}-${item.sectionLetter}`,
      },
    ],
  },
  {
    key: 'subjects',
    title: 'Fanlar',
    icon: 'menu_book',
    endpoint: '/api/subjects',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'name', label: 'Nomi', field: 'name', sortable: true, align: 'left' },
    ],
    fields: [{ key: 'name', label: 'Nomi', type: 'text', required: true }],
  },
  {
    key: 'positions',
    title: 'Lavozimlar',
    icon: 'badge',
    endpoint: '/api/positions',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'title', label: 'Nomi', field: 'title', sortable: true, align: 'left' },
    ],
    fields: [{ key: 'title', label: 'Nomi', type: 'text', required: true }],
  },
  {
    key: 'employees',
    title: 'Xodimlar',
    icon: 'work',
    endpoint: '/api/employees',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'fullName', label: "To'liq ism", field: 'fullName', sortable: true, align: 'left' },
      { name: 'phone', label: 'Telefon', field: 'phone', align: 'left' },
      { name: 'positionTitle', label: 'Lavozim', field: 'positionTitle', align: 'left' },
    ],
    fields: [
      { key: 'firstName', label: 'Ism', type: 'text', required: true },
      { key: 'lastName', label: 'Familiya', type: 'text', required: true },
      { key: 'phone', label: 'Telefon', type: 'text', required: true },
      {
        key: 'positionId',
        label: 'Lavozim',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/positions',
        optionValue: 'id',
        optionLabel: 'title',
      },
    ],
  },
  {
    key: 'lesson-slots',
    title: 'Dars jadvali',
    icon: 'schedule',
    endpoint: '/api/lesson-slots',
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'className', label: 'Sinf', field: 'className', align: 'left' },
      { name: 'subjectName', label: 'Fan', field: 'subjectName', align: 'left' },
      { name: 'employeeName', label: "O'qituvchi", field: 'employeeName', align: 'left' },
      { name: 'roomNumber', label: 'Xona', field: 'roomNumber', align: 'left' },
      { name: 'weekday', label: 'Kun', field: 'weekday', align: 'left' },
      { name: 'startTime', label: 'Boshlanish', field: 'startTime', align: 'left' },
      { name: 'endTime', label: 'Tugash', field: 'endTime', align: 'left' },
    ],
    fields: [
      {
        key: 'schoolClassId',
        label: 'Sinf',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/school-classes',
        optionValue: 'id',
        optionLabel: (item) => `${item.gradeNumber}-${item.sectionLetter}`,
      },
      {
        key: 'subjectId',
        label: 'Fan',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/subjects',
        optionValue: 'id',
        optionLabel: 'name',
      },
      {
        key: 'employeeId',
        label: "O'qituvchi",
        type: 'select',
        required: true,
        optionsEndpoint: '/api/employees',
        optionValue: 'id',
        optionLabel: 'fullName',
      },
      {
        key: 'roomId',
        label: 'Xona',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/rooms',
        optionValue: 'id',
        optionLabel: 'roomNumber',
      },
      {
        key: 'weekday',
        label: 'Hafta kuni',
        type: 'select',
        required: true,
        options: weekdayOptions,
      },
      { key: 'startTime', label: 'Boshlanish vaqti', type: 'time', required: true },
      { key: 'endTime', label: 'Tugash vaqti', type: 'time', required: true },
    ],
  },
  {
    key: 'users',
    title: 'Foydalanuvchilar',
    icon: 'manage_accounts',
    endpoint: '/api/users',
    adminOnly: true,
    columns: [
      { name: 'id', label: 'ID', field: 'id', sortable: true, align: 'left' },
      { name: 'username', label: 'Username', field: 'username', sortable: true, align: 'left' },
      { name: 'role', label: 'Rol', field: 'role', align: 'left' },
    ],
    fields: [
      { key: 'username', label: 'Username', type: 'text', required: true },
      {
        key: 'password',
        label: 'Parol',
        type: 'password',
        required: true,
        requiredOnCreateOnly: true,
        hint: 'Tahrirlashda bo\'sh qoldirilsa, eski parol saqlanadi',
      },
      { key: 'role', label: 'Rol', type: 'select', required: true, options: roleOptions },
    ],
  },
]

export function getModule(key) {
  return modules.find((m) => m.key === key)
}
