package uz.azizbek.maktabboshqaruv.entity;

public enum NotificationType {
    ATTENDANCE_ABSENT, ATTENDANCE_LATE, GRADE_NEW, GRADE_UPDATED, ANNOUNCEMENT,
    GRADE_LOW, TOMORROW_SCHEDULE, WEEKLY_REPORT, EVENT_REMINDER, MESSAGE_REPLY, ABSENCE_DECISION, BROADCAST
}
